// Generated by CoffeeScript 1.10.0
(function() {
  var error, fiona, log, tools;

  tools = require("../../src/js/tools");

  log = tools.console.log;

  error = tools.console.error;

  fiona = new tools.Voice('fiona');

  if (Math.random() > 0.5) {
    log("Success");
    fiona.say("Success");
  } else {
    error("Error!");
    fiona.say("Error!");
  }

}).call(this);
