// Generated by CoffeeScript 1.10.0
(function() {
  var Voice, error, fiona, log, tools;

  tools = require("../../src/js/tools");

  log = tools.console.log;

  error = tools.console.error;

  Voice = tools.Voice;

  fiona = new Voice('fiona');

  error("Error! No particular error, just testing...");

  log("Green looks better than white, right?");

  fiona.say("You english bastard");

}).call(this);
