// Generated by CoffeeScript 1.10.0
(function() {
  var listener, ws;

  ws = require("webspeech");

  console.log(ws);

  listener = new ws.SpeechRecognizer({
    language: 'en'
  });

  listener.on('bestResult', function(text) {
    return console.log("Recognized text: " + text);
  });

  listener.on('listen', function(event) {
    return console.log("Listening...");
  });

  listener.on('error', function(event) {
    return console.error(event);
  });

  listener.on('soundEnd', function(event) {
    return console.log("Listen finished");
  });

  listener.listen();

}).call(this);
