// Generated by CoffeeScript 1.10.0
(function() {
  var r;

  console.log("Running");

  r = new window.webkitSpeechRecognition();

  r.continuous = false;

  r.onresult = function(event) {
    return alert('result');
  };

  r.onerror = function(error) {
    return console.error(error);
  };

  r.start();

  setTimeout(function() {
    return r.stop();
  }, 10000);

}).call(this);
