// Generated by CoffeeScript 1.10.0
(function() {
  var colors;

  colors = require("colors");

  module.exports = {
    log: function(data) {
      return console.log(data.green);
    },
    error: function(error) {
      return console.log(error.red);
    }
  };

}).call(this);
