// Generated by CoffeeScript 1.10.0
(function() {
  var colors;

  colors = require("colors");

  module.exports = {
    log: function(data) {
      if (typeof data === 'object') {
        data = JSON.stringify(data);
      }
      return console.log(data.green);
    },
    error: function(error) {
      var data;
      if (typeof data === 'object') {
        data = JSON.stringify(data);
      }
      return console.log(error.red);
    }
  };

}).call(this);
