// Generated by CoffeeScript 1.10.0
(function() {
  var Question, exec, log, say;

  say = require("./say");

  exec = require("child_process").exec;

  log = function(data) {
    return console.log(data);
  };

  Question = (function() {
    function Question(voice) {
      this.voice = voice != null ? voice : 'daniel';
      this.question = "";
    }

    Question.prototype.ask = function(phrase) {
      var index;
      if (phrase != null) {
        this.phrase = phrase;
      }
      index = phrase.indexOf("?");
      if (index === -1) {
        phrase += "?";
      }
      return this.question = phrase;
    };

    Question.prototype.answer = function(phrase) {
      say(this.question, this.voice);
      return say(phrase, this.voice);
    };

    Question.prototype.yes = function(phrase) {
      return this.answer("yes, " + phrase);
    };

    Question.prototype.no = function(phrase) {
      return this.answer("no, " + phrase);
    };

    return Question;

  })();

  module.exports = Question;

}).call(this);
