// Generated by CoffeeScript 1.10.0
(function() {
  var Voice, console;

  Voice = require("./voice");

  console = require("./console");

  module.exports = {
    Voice: Voice,
    log: console.log,
    error: console.error
  };

}).call(this);
